### ISSUE TITLE
Allow re-snapshotting

### ISSUE THREAD

**Issue by cinnamon-msft** [JaneaSystems/PowerToys-DevProjects#27]
When editing a project, I should be able to move my windows around then take another snapshot to update the project

**Comment by donlaci** [comment]
@plante-msft 
The feature would be great to have, actually sooner or later we have to add it.
A proposal to consider:
We could have an "update" button somewhere in the top region of the editor page. 
When the user presses it, we would do a new snapshot of the current apps. 
For every newly found app we would:
- add it to the project if the app was not yet included. 
- add a button to the app with content "Update position" if the app is included but with different postion.
- ignore it if the app is already included with the same position.

Additionaly we could have some highlighting on the newly added apps or where the position-update is offered.

This solution might be satisfy also issue #53

**Comment by plante-msft** [comment]
@donlaci I think our ideal solution is a combination of #53 and this item.

For the first creation experience, we introduce a "setup" phase that #53 outlines which allows for a smoother creation flow and guides the user to create the basis for the project they want.

For ensuing update flows to the layout, we simply add the "update" button that you're proposing here. In addition to the update button, we should have an "undo" or "revert changes" buttons that reverts the re-snapshot changes so that the user isn't forced to cancel out of the editor for Project A and then re-enter if they wish to take a different snapshot.

**Comment by hamza-usmani** [comment]
Totally agreed. 2 phase solution here:
1. Add update button so users can quickly re-snapshot their windows
2. Add visual project creation state (#53) where the user can arrange their windows and hit "done"/"save" when they are ready to create the project. We have existing UI ideas for this that we can build off of:

![image](https://github.com/JaneaSystems/PowerToys-DevProjects/assets/15319966/abcac716-25db-49b6-b1d7-f49031ba97a4)

**Comment by SeraphimaZykova** [comment]
Closing in favor of https://github.com/JaneaSystems/PowerToys-DevProjects/issues/69
